### ISSUE TITLE
Hi I'm having a problem with my config

### ISSUE THREAD

**Issue by devbaraus** [Fickletcell/foodeffect#1]
I'm using the latest version of foodeffect on paper 1.19

Seems like the effect nausea is not working properly, when I eat rotten_flesh or spider_eye I get an error but any other food is working.  

This is my config.yml

```
#plugin by portal
# donot leave effect empty..
food:
  # cooked food
  cooked_mutton: 
    effect:
      - 'ABSORPTION'
    duration: 60
    amplifier: 1
    chance: 50
  cooked_porkchop: 
    effect: 
      - 'ABSORPTION'
    duration: 60
    amplifier: 1
    chance: 50
  cooked_salmon: 
    chance: 50
    effect: 
      - 'JUMP_BOOST'
    duration: 60
    amplifier: 1
  steak:
    chance: 50
    effect: 
      - 'ABSORPTION'
    duration: 60
    amplifier: 1
  baked_potato:
    chance: 50
    effect: 
      - 'RESISTANCE'
    duration: 60
    amplifier: 2
  cooked_chicken: 
    chance: 50
    effect: 
      - 'ABSORPTION'
    duration: 60
    amplifier: 1
  cooked_cod: 
    chance: 50
    effect: 
      - 'JUMP_BOOST'
    duration: 60
    amplifier: 1
  cooked_rabbit: 
    effect: 
      - 'JUMP_BOOST'
    duration: 60
    amplifier: 1
#raw food
  potato: 
    chance: 50
    effect: 
      - 'RESISTANCE'
    duration: 20
    amplifier: 1
  raw_beef:
    chance: 50
    effect: 
      - 'WEAKNESS'
    duration: 60
    amplifier: 1
  raw_chicken:
    chance: 50 
    effect: 
      - 'WEAKNESS'
    duration: 60
    amplifier: 1
  raw_mutton: 
    chance: 50
    effect: 
      - 'WEAKNESS'
    duration: 60
    amplifier: 1
  raw_porkchop: 
    chance: 50
    effect: 
      - 'WEAKNESS'
    duration: 60
    amplifier: 1
  raw_rabbit: 
    chance: 50
    effect: 
      - 'WEAKNESS'
    duration: 60
    amplifier: 1
  raw_cod: 
    chance: 50
    effect: 
      - 'WATER_BREATHING'
    duration: 60
    amplifier: 1
  raw_salmon: 
    chance: 50
    effect: 
      - 'WATER_BREATHING'
    duration: 60
    amplifier: 1
#items
  enchanted_golden_apple: 
    chance: 0
    effect: 
      - 'JUMP_BOOST'
    duration: 60
    amplifier: 1
  golden_apple: 
    chance: 50
    effect: 
      - 'HASTE'
    duration: 60
    amplifier: 2
  apple: 
    chance: 50
    effect: 
      - 'HASTE'
    duration: 60
    amplifier: 1
  beetroot: 
    chance: 50
    effect: 
      - 'STRENGTH'
    duration: 60
    amplifier: 1
  beetroot_soup: 
    chance: 50
    effect: 
      - 'STRENGTH'
    duration: 60
    amplifier: 2
  bread: 
    chance: 50
    effect: 
      - 'REGENERATION'
    duration: 60
    amplifier: 1
  golden_carrot: 
    chance: 50
    effect: 
      - 'FIRE_RESISTANCE'
    duration: 60
    amplifier: 1
  carrot: 
    chance: 50
    effect: 
      - 'REGENERATION'
    duration: 60
    amplifier: 1
  mushroom_stew: 
    chance: 50
    effect: 
      - 'HEALTH_BOOST'
    duration: 60
    amplifier: 1
  rabbit_stew: 
    chance: 50
    effect: 
      - 'SATURATION'
    duration: 60
    amplifier: 1
  suspicious_stew: 
    chance: 0
    effect: 
      - 'SLOW_FALLING'
    duration: 60
    amplifier: 1
  chorus_fruit: 
    chance: 50
    effect: 
      - 'INVISIBILITY'
    duration: 60
    amplifier: 1
  dried_kelp: 
    chance: 50
    effect: 
     - 'DOLPHINS_GRACE'
    duration: 60
    amplifier: 1
  melon_slice: 
    chance: 50
    effect: 
      - 'HEALTH_BOOST'
    duration: 60
    amplifier: 1
  poisonous_potato: 
    chance: 50
    effect: 
      - 'POISON'
    duration: 60
    amplifier: 1
  pimpkin_pie: 
    chance: 50
    effect: 
      - 'SPEED'
      - 'JUMP_BOOST'
    duration: 60
    amplifier: 1
  sweet_berries: 
    chance: 50
    effect: 
      - 'WEAKNESS'
    duration: 60
    amplifier: 1
  cookie: 
    chance: 50
    effect: 
      - 'JUMP_BOOST'
    duration: 60
    amplifier: 1
  glow_berries: 
    chance: 50
    effect: 
      - 'GLOWING'
    duration: 60
    amplifier: 1
  honey_bottle:
    chance: 50 
    effect: 
      - 'SPEED'
      - 'JUMP_BOOST'
    duration: 60
    amplifier: 1
  rotten_flesh: 
    chance: 50
    effect: 
      - 'NAUSEA'
    duration: 60
    amplifier: 1
  spider_eye: 
    chance: 50
    effect: 
      - 'NAUSEA'
    duration: 60
    amplifier: 1
  tropical_fish: 
    chance: 50
    effect: 
      - 'WATER_BREATHING'
    duration: 60
    amplifier: 1
```

This is the error I get when eating food with nausea effect

```
Could not pass event PlayerItemConsumeEvent to Foodeffect v2.7
java.lang.IllegalArgumentException: effect type cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:67) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:92) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at vb.$foodeffect.PluginMain.event1(PluginMain.java:874) ~[foodeffect-2.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor588.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-69]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:3851) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:1716) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:3712) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2320) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:3693) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2910) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:276) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:675) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:340) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:568) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:232) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1581) ~[paper-1.19.jar:git-Paper-69]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-69]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by devbaraus** [comment]
JUMP_BOOST seems to not work as well

**Comment by devbaraus** [comment]
I found out that you use the same names used on spigot API, so I changed some of them and it worked.
